# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: DEBUG
    io.github.jhipster: DEBUG
    com.techvg.covid.care: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web.client.RestTemplate: DEBUG

spring:
  profiles:
    active: dev
    include:
      - swagger
      # Uncomment to activate TLS for the dev profile
      #- tls
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    #addresses: ccms.update.facility.info.queue

  #ccms.update.facility.info.queue: ccms.update.facility.info.queue

  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/covidcare?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    show-sql: true
  liquibase:
    contexts: dev
  mail:
    host: localhost
    port: 25
    username:
    password:
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false

server:
  port: 8181

icmr:
  shouldFetchData: true
  patient:
    count:
      queue: 'local.icmr.patients.count.queue'
#      dlq: 'local.icmr.patient.info.queue.dlq'
#      queue: 'local.icmr.patient.info.queue'

ccms:
  hospital:
    queue:
      info: 'ccms.update.hospital.odas_facility_id_queue'
captcha:
  google:
    secret:
      key: 6LfZ9nUdAAAAABwTlrKOcHSRS791PPjFL95ut99y
      url: https://www.google.com/recaptcha/api/siteverify

ODAS:
  shouldSendData: true
  dlq: 'ccms.odas.falicity.info.dlq'
  Queue:
    facility:
      info: 'ccms.update.facility.info.queue'
    bed:
      info: 'ccms.update.facility.bed.info.queue'
      occupancy: 'ccms.update.facility.bed.occupancy.queue'
    oxygen:
      info: 'ccms.update.facility.oxygen.info.queue'
      consumption: 'ccms.update.oxygen.consumption.queue'

isolation:
  shouldSendData: true
  username: admin
  password: admin
  authenticate: 'http://localhost:8185/api/authenticate'
  count: 'http://localhost:8185/api/isolations/count'
  list: 'http://localhost:8185/api/isolations'

custom:
  jasper:
    url: http://135.181.100.62:7010/jasperserver/rest_v2/reports/Qa
    username: jasperadmin
    password: jasperadmin

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
  cache: # Cache configuration
    ehcache: # Ehcache configuration
      time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache
      max-entries: 100 # Number of objects in each cache entry
  # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: MWZlMjRjZjA1NGY0YWRlNTA1MTVhODEwZWZhMzU5Zjg0MWZiNDVkNTI2N2Y2NzBmNjQ0YTJiZDAzYWI0YjkwMzJiNzE2MmE1YjBkMmYwOGZhOTlmOWFjNjNmMzlhOWM4YzEwMGU3MGUwOWRiOGI2NDM0NDRjYTI3OWZkMDNhYTg=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail: # specific JHipster mail property, for standard properties see MailProperties
    base-url: http://127.0.0.1:8181
  metrics:
    logs: # Reports metrics in the logs
      enabled: false
      report-frequency: 60 # in seconds
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512
  audit-events:
    retention-period: 30 # Number of days before audit events are deleted.

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

# application:
